### ISSUE TITLE
No latest tag on the docker containers

### ISSUE THREAD

**Issue by MrDiba** [apache/openwhisk-runtime-php#135]
As of 4 months ago there is no `latest` tag on the docker images hosted on <https://hub.docker.com>.

For example taking the [php-v8.2 image](https://hub.docker.com/r/openwhisk/action-php-v8.2/tags). It only contains the short commit tag and the nightly tag, as specified [here](https://github.com/apache/openwhisk-runtime-php/blob/master/.github/workflows/ci.yaml#L95-L96).

The [php-v8.1 image](https://hub.docker.com/r/openwhisk/action-php-v8.1/tags) contains a lot more tags, including release tags, but these tags are already 4 months old. 

If this is a 'feature' then the readme is wrong and should be updated. 

If this is a bug, how can I help?

**Comment by dgrove-oss** [comment]
With summer vacations, somehow we never got around to making an official release that included the php 8.2 support added in #134.   Only Apache releases get the `latest` tag.   We'll get the voting process started and get a release out by next week.

**Comment by dgrove-oss** [comment]
1.19.0 release completed.  Images with the 1.19.0 are available on docker hub and the `latest` tag in php 8.0, 8.1, and 8.2 has been updated to be an alias for the 1.19.0 tag.
